/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const VocabularyItem = IDL.Record({
  'id' : IDL.Nat,
  'timesIncorrect' : IDL.Nat,
  'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
  'word' : IDL.Text,
  'translation' : IDL.Text,
  'notes' : IDL.Opt(IDL.Text),
  'timesCorrect' : IDL.Nat,
  'lastSeen' : IDL.Opt(Time),
});
export const LanguageSettings = IDL.Record({
  'sourceLanguage' : IDL.Text,
  'targetLanguage' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'practiceCounter' : IDL.Nat,
  'activeLanguage' : LanguageSettings,
  'vocabulary' : IDL.Vec(VocabularyItem),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addVocabularyItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Vec(IDL.Text))],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteVocabularyItem' : IDL.Func([IDL.Nat], [], []),
  'getAllVocabularyItems' : IDL.Func([], [IDL.Vec(VocabularyItem)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getItemsDueForReview' : IDL.Func([], [IDL.Vec(VocabularyItem)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'initializeUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitPracticeResult' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const VocabularyItem = IDL.Record({
    'id' : IDL.Nat,
    'timesIncorrect' : IDL.Nat,
    'tags' : IDL.Opt(IDL.Vec(IDL.Text)),
    'word' : IDL.Text,
    'translation' : IDL.Text,
    'notes' : IDL.Opt(IDL.Text),
    'timesCorrect' : IDL.Nat,
    'lastSeen' : IDL.Opt(Time),
  });
  const LanguageSettings = IDL.Record({
    'sourceLanguage' : IDL.Text,
    'targetLanguage' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'practiceCounter' : IDL.Nat,
    'activeLanguage' : LanguageSettings,
    'vocabulary' : IDL.Vec(VocabularyItem),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addVocabularyItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Vec(IDL.Text))],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteVocabularyItem' : IDL.Func([IDL.Nat], [], []),
    'getAllVocabularyItems' : IDL.Func(
        [],
        [IDL.Vec(VocabularyItem)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getItemsDueForReview' : IDL.Func([], [IDL.Vec(VocabularyItem)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'initializeUser' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitPracticeResult' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };