/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface LanguageSettings {
  'sourceLanguage' : string,
  'targetLanguage' : string,
}
export type Time = bigint;
export interface UserProfile {
  'practiceCounter' : bigint,
  'activeLanguage' : LanguageSettings,
  'vocabulary' : Array<VocabularyItem>,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VocabularyItem {
  'id' : bigint,
  'timesIncorrect' : bigint,
  'tags' : [] | [Array<string>],
  'word' : string,
  'translation' : string,
  'notes' : [] | [string],
  'timesCorrect' : bigint,
  'lastSeen' : [] | [Time],
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addVocabularyItem' : ActorMethod<
    [string, string, [] | [string], [] | [Array<string>]],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteVocabularyItem' : ActorMethod<[bigint], undefined>,
  'getAllVocabularyItems' : ActorMethod<[], Array<VocabularyItem>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getItemsDueForReview' : ActorMethod<[], Array<VocabularyItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initializeUser' : ActorMethod<[string, string], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'submitPracticeResult' : ActorMethod<[bigint, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];